# https://github.com/openethereum/openethereum/blob/main/parity/cli/presets/config.non-standard-ports.toml
[network]
# OpenEthereum will listen for connections on port 30305.
port = 30305

[rpc]
# JSON-RPC over HTTP will be accessible on port 8645.
port = 8645