{{- range $idx, $value := .Values.configmaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ tpl $value.name $ }}
data:
  {{- range $k, $v := $value.data }}
  {{ $k }}: | 
{{ (tpl $v $) | indent 4 }}
  {{- end }}
---
{{- end }}