{{- if gt (len .Values.containers) 0 }}
apiVersion: apps/v1
kind: {{ .Values.kind }}
metadata:
  name: {{ include "base.fullname" . }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "base.selectorLabels" . | nindent 6 }}
  {{- if eq .Values.kind "StatefulSet"  }}
  serviceName: {{ include "base.fullname" . }}
  {{- end }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      {{- with .Values.annotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "base.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "base.serviceAccountName" . }}
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        {{- range $i, $v := .Values.initContainers }}
        - name: "{{ $.Chart.Name }}-init-{{ $i }}"
          {{- include "base.image" $v.image | indent 10 }}
          {{- include "base.ports" $v.ports | indent 10 }}
          {{- include "base.env" $ | indent 10 }}
          {{- include "base.volumeMounts" $v.volumeMounts | indent 10 }}
          {{- with $v.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
      containers:
        {{- range $i, $v := .Values.containers }}
        - name: "{{ $.Chart.Name }}-{{ $i }}"
          {{- include "base.image" $v.image | indent 10 }}
          {{- include "base.ports" $v.ports | indent 10 }}
          {{- include "base.env" $ | indent 10 }}
          {{- include "base.volumeMounts" $v.volumeMounts | indent 10 }}
          {{- with $v.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- include "base.volumes" . | indent 6 }}
  {{- include "base.volumeClaimTemplates" . | indent 2 }}
{{- end }}