apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "chainlink.fullname" . }}
  labels:
    {{- include "chainlink.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chainlink.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "chainlink.fullname" . }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chainlink.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "chainlink.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: 
            {{- toYaml .Values.image.command | nindent 12 }}
          args: 
            {{- toYaml .Values.image.args | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.container.ports.http }}
              protocol: TCP
            - name: listener
              containerPort: {{ .Values.container.ports.listener }}
              protocol: TCP
            - name: listener2
              containerPort: {{ .Values.container.ports.listener2 }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: {{ include "chainlink.fullname" . }}-configmap
          volumeMounts:
            - name: config
              mountPath: {{ .Values.volumes.config.mountPath }}
            - name: configToml
              mountPath: {{ .Values.volumes.configToml.mountPath }}
            - name: secretsToml
              mountPath: {{ .Values.volumes.secretsToml.mountPath }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "chainlink.fullname" . }}-configmap
            items:
            - key: API_LOGIN
              path: api
            - key: WALLET_PASSWORD
              path: password
        - name: configToml
          configMap:
            name: {{ include "chainlink.fullname" . }}-config-toml
            items:
            - key: value
              path: config.toml
        - name: secretsToml
          secretsMap:
            name: {{ include "chainlink.fullname" . }}-secrets-toml
            items:
            - key: value
              path: secrets.toml
