{{- range $idx, $value := .Values.MachineDeployments }}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  labels:
    nodepool: {{ $value.name }}
  name: {{ $value.name }}
spec:
  clusterName: {{ $.Values.Cluster.name }}
  replicas: {{ $value.replicas }}
  selector: {}
  template:
    metadata:
      labels:
        nodepool: {{ $value.name }}
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: {{ $.Values.KubeadmConfigTemplate.name }}
      clusterName: {{ $.Values.Cluster.name }}
      failureDomain: {{ $value.failureDomain }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: {{ $value.infrastructureRef.kind }}
        name: {{ $value.infrastructureRef.name }}
      version: 1.24.0

---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: {{ $value.name }}-unhealthy-5m
  namespace: default
spec:
  clusterName: {{ $.Values.Cluster.name }}
  maxUnhealthy: 100%
  nodeStartupTimeout: {{ $value.nodeStartupTimeout }}
  selector:
    matchLabels:
      nodepool: {{ $value.name }}
  unhealthyConditions:
    - status: Unknown
      timeout: 300s
      type: Ready
    - status: "False"
      timeout: 300s
      type: Ready

---


---
{{- end }}