apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.Cluster.name }}-hetzner
  labels:
    clusterctl.cluster.x-k8s.io/move: ""
type: Opaque
stringData:
  hcloud: {{ .Values.secret.hcloud | quote }}
  robot-password: {{ .Values.secret.robotPassword | quote }}
  robot-user:  {{ .Values.secret.robotUser | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.Cluster.name }}-robot-ssh
  labels:
    clusterctl.cluster.x-k8s.io/move: ""
type: Opaque
stringData:
  sshkey-name: {{ .Values.secret.robotSSHKeyName | quote }}
  ssh-privatekey: |-
    {{ .Values.secret.robotSSHPrivateKey | nindent 4 }}
  ssh-publickey: {{ .Values.secret.robotSSHPublicKey }}