apiVersion: v1
kind: Service
metadata:
  name: {{include "chainlink-adapter.fullname" .}}
  labels: {{- include "chainlink-adapter.labels" . | nindent 4}}
spec:
  type: {{.Values.service.http.type}}
  ports:
    - port: {{.Values.service.http.port}}
      targetPort: http
      protocol: TCP
      name: http
    {{ if .Values.prometheus }}
    - port: {{.Values.service.prometheus.port}}
      targetPort: prometheus
      protocol: TCP
      name: prometheus
    {{ end }}
  selector: {{- include "chainlink-adapter.selectorLabels" . | nindent 4}}
