{{ if .Values.prometheus }}

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "starter-chart.fullname" . }}-prometheus
spec:
  endpoints:
  - interval: 5s
    path: /metrics
    port: prometheus
    metricRelabelings:
    - sourceLabels: [__name__]
      targetLabel: __name__
      replacement: starter-chart_$1
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace}}
  selector:
    matchLabels:
      {{- include "starter-chart.selectorLabels" . | nindent 6 }}

{{ end }}