apiVersion: v1
kind: Service
metadata:
  name: {{ include "starter-chart.fullname" . }}
  labels:
    {{- include "starter-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.http.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "starter-chart.selectorLabels" . | nindent 4 }}


---

{{- if (.Values.prometheus) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "starter-chart.fullname" . }}
  labels:
    {{- include "starter-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.prometheus.type }}
  ports:
    - port: {{ .Values.service.prometheus.port }}
      targetPort: prometheus
      protocol: TCP
      name: prometheus
  selector:
    {{- include "starter-chart.selectorLabels" . | nindent 4 }}
{{- end -}}