apiVersion: v1
kind: Service
metadata:
  name: {{ include "rskj.fullname" . }}
  labels:
    {{- include "rskj.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.ws }}
      targetPort: ws
      protocol: TCP
      name: ws
  selector:
    {{- include "rskj.selectorLabels" . | nindent 4 }}
