apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-http-ws-proxy.fullname" . }}
  labels:
    {{- include "nginx-http-ws-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.nginx }}
      targetPort: nginx
      protocol: TCP
      name: nginx
  selector:
    {{- include "nginx-http-ws-proxy.selectorLabels" . | nindent 4 }}