apiVersion: v2
name: graphprotocol-querynode
description: A Helm chart for Graph Protocol Query Node
type: application
version: 0.3.1
icon: https://vulcanlink.github.io/charts/assets/img/thegraph.png
keywords:
  - graphprotocol
  - ethereum

home: https://thegraph.com/
sources:
  - https://github.com/graphprotocol/graph-node 
maintainers:
  - name: Leo Vigna
    email: leo@vulcan.link

appVersion: latest
