# https://github.com/openethereum/openethereum/blob/main/parity/cli/presets/config.dev-insecure.toml
[parity]
chain = "dev"

[mining]
reseal_min_period = 0
min_gas_price = 0

[rpc]
interface = "all"
apis = ["all"]
hosts = ["all"]