[parity]
chain = "mainnet"

[rpc]
disable = false
port = 8545
interface = "local"
cors = ["null"]
apis = ["web3", "eth", "net"]
hosts = ["none"]
allow_missing_blocks = false

[websockets]
disable = false
port = 8546
interface = "local"
origins = ["none"]
apis = ["web3", "eth", "net"]
hosts = ["none"]

[ipc]
disable = false
apis = ["web3", "eth", "net"]