apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "matic.fullname" . }}
  labels:
    {{- include "matic.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "matic.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "matic.fullname" . }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "matic.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "matic.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-heimdalld
          image: busybox:1.28
          command: ["sh", "-c", "cp -r /config /var/lib/heimdalld"]
          volumeMounts:
            - name: heimdall-vol 
              mountPath: /var/lib/heimdalld
            - name: config-vol
              mountPath: /config
      containers:
        - name: {{ .Chart.Name }}-heimdalld
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.heimdalld.repository }}:{{ .Values.image.heimdalld.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.heimdalld.pullPolicy }}
          command: 
            {{- toYaml .Values.image.heimdalld.command | nindent 12 }}
          args: 
            {{- toYaml .Values.image.heimdalld.args | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.container.ports.http }}
              protocol: TCP
            - name: ws
              containerPort: {{ .Values.container.ports.ws }}
              protocol: TCP
          volumeMounts:
            - name: heimdall-vol 
              mountPath: /var/lib/heimdalld
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config-vol
          configMap:
            name: {{ include "matic.fullname" . }}-configmap
            items:
              - key: genesis.json
                path: genesis.json
              - key: config.toml
                path: config.toml
              - key: heimdall-config.toml
                path: heimdall-config.toml
{{- if and .Values.persistence.enabled .Values.persistence.existingClaim }}
        - name: heimdall-vol
          persistentVolumeClaim:
{{- with .Values.persistence.existingClaim }}
            claimName: {{ tpl . $ }}
{{- end }}
{{- else if not .Values.persistence.enabled }}
        - name: heimdall-vol
          emptyDir: {}
{{- else if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
  volumeClaimTemplates:
    - metadata:
        name: heimdall-vol
      {{- with .Values.persistence.annotations }}
        annotations:
        {{- range $key, $value := . }}
            {{ $key }}: {{ $value }}
        {{- end }}
      {{- end }}
      spec:
        accessModes:
        {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
        {{ include "matic.storageClass" . }}
{{- end }}