# Default values for chainlink.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: smartcontract/chainlink
  pullPolicy: IfNotPresent
  command: ["chainlink", "local", "node"]
  args: ["-a", "/etc/chainlink/api", "-p", "/etc/chainlink/password", "-c", "/etc/chainlink/config.toml", "-s", "/etc/chainlink/secrets.toml"]
config:
  # Login Info
  ROOT: /chainlink
  API_LOGIN: |
    API_EMAIL
    API_LOGIN
  WALLET_PASSWORD: ""
  # HTTP Security
  ALLOW_ORIGINS: "*"
  SECURE_COOKIES: "false"
  CHAINLINK_PORT: "6688"
  CHAINLINK_TLS_PORT: "0"
  # Database
  # DATABASE_TIMEOUT: "0"
  DATABASE_URL: postgresql://postgres@postgresql:5432/chainlink?sslmode=disable
  # Ethereum
  ETH_URL: ws://geth:8546
  ETH_CHAIN_ID: "1"
  LINK_CONTRACT_ADDRESS: 0x514910771af9ca656af840dff83e8264ecf986ca
  ### Logging ###
  # JSON_CONSOLE: "true"
  # LOG_LEVEL: warn
  # LOG_TO_DISK: "false"
  ### Secondary Ethereum Node ###
  # ETH_SECONDARY_URL: ""
  ### Chainlink Explorer ###
  # EXPLORER_ACCESS_KEY: ""
  # EXPLORER_SECRET: ""
  # EXPLORER_URL: wss://explorer.chain.link
  ### Gas Bumber ###
  # GAS_UPDATER_ENABLED: "true"
  # GAS_UPDATER_TRANSACTION_PERCENTILE: "71"
  # ETH_GAS_PRICE_DEFAULT: "1000000000"
  # ETH_GAS_BUMP_THRESHOLD: "5"
  # ETH_GAS_BUMP_WEI: "20000000000"
  # ETH_GAS_BUMP_PERCENT: "20"
  # ETH_MAX_GAS_PRICE_WEI: "2500000000000"
  ### Transaction Manager ###
  # CHAINLINK_TX_ATTEMPT_LIMIT: "25"
  # ETH_MAX_IN_FLIGHT_TRANSACTIONS: "128"
  # MIN_OUTGOING_CONFIRMATIONS: "2"
  # MINIMUM_CONTRACT_PAYMENT: "50000000000000000"
  ### Fluxmonitor Variables ###
  # ORACLE_CONTRACT_ADDRESS: ""
  # FLAGS_CONTRACT_ADDRESS: ""
  ### OCR Variables ###
  # OCR_TRACE_LOGGING: "true"
  # FEATURE_OFFCHAIN_REPORTING: "true"
  # P2P_LISTEN_PORT: "30668"
  # P2P_ANNOUNCE_PORT: "30668"
  # P2P_ANNOUNCE_IP: "YOUR_NODE_IP"
  ### OCR Default job config ###
  # OCR_KEY_BUNDLE_ID: ""
  # P2P_PEER_ID: ""
  # OCR_TRANSMITTER_ADDRESS: ""
  # P2P_BOOTSTRAP_PEERS: ""
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

container:
  ports:
    http: 6688
    listener: 30668
    listener2: 30669

volumes:
  config:
    mountPath: /etc/chainlink
  configToml:
    mountPath: /etc/chainlink
  secretsToml:
    mountPath: /etc/chainlink

service:
  type: ClusterIP
  http: 6688

serviceP2P:
  type: ClusterIP #Ignored, only created if NodePort
  listener: 30668

serviceP2PV2:
  type: ClusterIP #Ignored, only created if NodePort
  listener2: 30669

prometheus: false

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

configToml: ''
secretsToml: ''
