{{ if .Values.prometheus }}

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "geth.fullname" . }}-metrics
spec:
  endpoints:
  - interval: 5s
    path: {{ .Values.prometheusServiceMonitor.path }}
    port: prometheus
    metricRelabelings:
    - sourceLabels: [__name__]
      targetLabel: __name__
      replacement: geth_$1
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace}}
  selector:
    matchLabels:
      {{- include "geth.selectorLabels" . | nindent 6 }}

{{ end }}