apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "geth.fullname" . }}
  labels:
    {{- include "geth.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "geth.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "geth.fullname" . }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "geth.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "geth.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- range $key, $value := . }}
        - name: "{{ $.Chart.Name }}-init-{{ $key }}"
          image: "{{ $value.image.repository }}:{{ $value.image.tag }}"
          imagePullPolicy: {{ $value.image.pullPolicy }}
          command:
            {{- toYaml $value.image.command | nindent 12 }}
          args: 
            {{- toYaml $value.image.args | nindent 12 }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            {{ if $.Values.secrets.influxdb }}
            - name: INFLUXDB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.secrets.influxdb }}
                  key: username
            - name: INFLUXDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.secrets.influxdb }}
                  key: password
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "geth.fullname" $ }}-env-configmap
          volumeMounts:
            - name: data
              mountPath: {{ $.Values.volumes.data.mountPath }}
            - name: config
              mountPath: {{ $.Values.volumes.config.mountPath }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: 
            {{- toYaml .Values.image.command | nindent 12 }}
          args: 
            {{- toYaml .Values.image.args | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.container.ports.http }}
              protocol: TCP
            - name: ws
              containerPort: {{ .Values.container.ports.ws }}
              protocol: TCP
            - name: prometheus
              containerPort: {{ .Values.container.ports.prometheus }}
              protocol: TCP
            - name: listener
              containerPort: {{ .Values.container.ports.listener }}
              protocol: TCP
            - name: discovery
              containerPort: {{ .Values.container.ports.discovery }}
              protocol: UDP
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            {{ if .Values.secrets.influxdb }}
            - name: INFLUXDB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.influxdb }}
                  key: username
            - name: INFLUXDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.influxdb }}
                  key: password
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "geth.fullname" . }}-env-configmap
          volumeMounts:
            - name: data
              mountPath: {{ .Values.volumes.data.mountPath }}
            - name: config
              mountPath: {{ .Values.volumes.config.mountPath }}
            {{ if .Values.key }}
            - name: key
              mountPath: {{ .Values.volumes.data.mountPath }}/keystore/key.json
              subPath: key.json
              readOnly: true
            {{- end }}
            {{ if .Values.password }}
            - name: password
              mountPath: {{ .Values.volumes.data.mountPath }}/password
              subPath: password
              readOnly: true
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "geth.fullname" . }}-files-configmap
        {{ if .Values.key }}
        - name: key
          secret:
            secretName: {{ include "geth.fullname" . }}-key
        {{- end }}
        {{ if .Values.password }}
        - name: password
          secret:
            secretName: {{ include "geth.fullname" . }}-password
        {{- end }}
{{- if and .Values.persistence.enabled .Values.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
{{- with .Values.persistence.existingClaim }}
            claimName: {{ tpl . $ }}
{{- end }}
{{- else if and .Values.persistence.enabled .Values.persistence.hostPath }}
        - name: data
          hostPath:
            path: {{ .Values.persistence.hostPath.path }}
            type: {{ .Values.persistence.hostPath.type }}
{{- else if not .Values.persistence.enabled }}
        - name: data
          emptyDir: {}
{{- else if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
  volumeClaimTemplates:
    - metadata:
        name: data
      {{- with .Values.persistence.annotations }}
        annotations:
        {{- range $key, $value := . }}
            {{ $key }}: {{ $value }}
        {{- end }}
      {{- end }}
      spec:
        accessModes:
        {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
        {{ include "geth.storageClass" . }}
{{- end }}