apiVersion: v2
name: graphprotocol
description: A Helm chart bundling Graph Protocol subcharts (agent, indexnode, querynode, service)
type: application
version: 0.3.1
icon: https://vulcanlink.github.io/charts/assets/img/thegraph.png
keywords:
  - graphprotocol
  - ethereum

home: https://thegraph.com/
sources:
  - https://github.com/graphprotocol
maintainers:
  - name: Leo Vigna
    email: leo@vulcan.link

appVersion: 1.0.0

dependencies:
    - name: graphprotocol-agent
      version: 0.3.1
      condition: graphprotocol-agent.enabled
      repository: file://../graphprotocol-agent
    - name: graphprotocol-indexnode
      version: 0.3.1
      condition: graphprotocol-indexnode.enabled
      repository: file://../graphprotocol-indexnode
    - name: graphprotocol-querynode
      version: 0.3.1
      condition: graphprotocol-querynode.enabled
      repository: file://../graphprotocol-querynode
    - name: graphprotocol-service
      version: 0.3.1
      condition: graphprotocol-service.enabled
      repository: file://../graphprotocol-service