[rpc]
disable = false
port = 8545
interface = "local"
cors = ["null"]
apis = ["web3", "eth", "traces"]
hosts = ["none"]
# processing_threads = 4 # RPC query CPU data
# server_threads = 4 # HTTP decoding threads
# max_payload = 1024 # 1024MB max payload

[websockets]
disable = false
port = 8546
interface = "local"
origins = ["none"]
apis = ["web3", "eth", "traces"]
hosts = ["none"]

[metrics]
enable = true

[ipc]
disable = true