[parity]
mode = "last"
mode_timeout = 300
mode_alarm = 3600
no_persistent_txqueue = false

chain = "mainnet"
base_path = "$HOME/parity"
db_path = "$HOME/parity/chains"
keys_path = "$HOME/parity/keys"

[network]
warp = false

[footprint]
tracing = "on"
pruning = "archive"
# cache_size = 2048 #[MB]
# scale_verifiers = true
# num_verifiers = 4

[snapshots]
enable = false

[misc]
logging = "own_tx=trace"
log_file = "/var/log/openethereum.log"
color = true