nameOverride: mainnet-heimdall

# Use custom configmap to avoid issue where helm can only access parent chart (base) files
configmap:
  name: '{{ include "base.fullname" . }}-files'
  data:
    genesis.json: '{{ $.Files.Get "files/mainnet/genesis.json" }}'
    app.toml: |
      minimum-gas-prices = ""
      halt-height = 0
      halt-time = 0
    config.toml: |

      proxy_app = "tcp://127.0.0.1:26658"
      moniker = "vulcanlink-matic-heimdall"
      fast_sync = true
      db_backend = "goleveldb"
      db_dir = "data"
      log_level = "main:info,state:info,*:error"
      log_format = "plain"
      genesis_file = "config/genesis.json"
      priv_validator_key_file = "config/priv_validator_key.json"
      priv_validator_state_file = "data/priv_validator_state.json"
      priv_validator_laddr = ""
      node_key_file = "config/node_key.json"
      abci = "socket"
      prof_laddr = "localhost:6060"
      filter_peers = false
      [rpc]
      laddr = "tcp://127.0.0.1:26657"
      cors_allowed_origins = []
      cors_allowed_methods = ["HEAD", "GET", "POST", ]
      cors_allowed_headers = ["Origin", "Accept", "Content-Type", "X-Requested-With", "X-Server-Time", ]
      grpc_laddr = ""
      grpc_max_open_connections = 900
      unsafe = false
      max_open_connections = 900
      max_subscription_clients = 100
      max_subscriptions_per_client = 5
      timeout_broadcast_tx_commit = "10s"
      max_body_bytes = 1000000
      max_header_bytes = 1048576
      tls_cert_file = ""
      tls_key_file = ""
      [p2p]
      laddr = "tcp://0.0.0.0:30306"
      external_address = ""
      seeds = "f4f605d60b8ffaaf15240564e58a81103510631c@159.203.9.164:30306,4fb1bc820088764a564d4f66bba1963d47d82329@44.232.55.71:26656"
      persistent_peers = ""
      upnp = false
      addr_book_file = "config/addrbook.json"
      addr_book_strict = true
      max_num_inbound_peers = 40
      max_num_outbound_peers = 10
      flush_throttle_timeout = "100ms"
      max_packet_msg_payload_size = 1024
      send_rate = 5120000
      recv_rate = 5120000
      pex = true
      seed_mode = false
      private_peer_ids = ""
      allow_duplicate_ip = false
      handshake_timeout = "20s"
      dial_timeout = "3s"
      [mempool]
      recheck = true
      broadcast = true
      wal_dir = ""
      size = 5000
      max_txs_bytes = 1073741824
      cache_size = 10000
      max_tx_bytes = 1048576
      [fastsync]
      version = "v0"
      [consensus]
      wal_file = "data/cs.wal/wal"
      timeout_propose = "3s"
      timeout_propose_delta = "500ms"
      timeout_prevote = "1s"
      timeout_prevote_delta = "500ms"
      timeout_precommit = "1s"
      timeout_precommit_delta = "500ms"
      timeout_commit = "5s"
      skip_timeout_commit = false
      create_empty_blocks = true
      create_empty_blocks_interval = "0s"
      peer_gossip_sleep_duration = "100ms"
      peer_query_maj23_sleep_duration = "2s"
      [tx_index]
      indexer = "kv"
      index_tags = ""
      index_all_tags = true
      [instrumentation]
      prometheus = false
      prometheus_listen_addr = ":6060"
      max_open_connections = 3
      namespace = "tendermint"
    heimdall-config.toml: |

      eth_rpc_url = "http://mainnet-rpc.ethereum:8545"
      bor_rpc_url = "http://mainnet-bor-rpc.matic:8545"
      tendermint_rpc_url = "http://0.0.0.0:26657"
      heimdall_rest_server = "http://0.0.0.0:1317"
      amqp_url = "amqp://guest:guest@rabbitmq.default:5672/"
      checkpoint_poll_interval = "5m0s"
      syncer_poll_interval = "1m0s"
      noack_poll_interval = "16m50s"
      clerk_poll_interval = "10s"
      span_poll_interval = "1m0s"
      main_chain_gas_limit = "5000000"
      no_ack_wait_time = "30m0s"

base:
  nameOverride: mainnet-heimdall
  ## Initialize with config files
  initContainers:
    - image:
        repository: maticnetwork/heimdall
        pullPolicy: IfNotPresent
        tag: "v0.2.9"
        command: ["bash"]
        args: [
            "-c",
            "heimdalld init &&
            cp /root/files/app.toml /root/.heimdalld/config/app.toml &&
            cp /root/files/config.toml /root/.heimdalld/config/config.toml &&
            cp /root/files/heimdall-config.toml /root/.heimdalld/config/heimdall-config.toml &&
            cp /root/files/genesis.json /root/.heimdalld/config/genesis.json",
          ]
      volumeMounts:
        - name: files
          mountPath: /root/files
        - name: data
          mountPath: /root/.heimdalld
  containers:
    - image:
        repository: maticnetwork/heimdall
        pullPolicy: IfNotPresent
        tag: "v0.2.9"
        command: ["heimdalld", "start"]
        args: []
      ports:
        - name: rpc
          containerPort: 26657
        - name: prometheus
          containerPort: 6060
        - name: listener
          containerPort: 30306
        - name: proxy-app
          containerPort: 26658
      volumeMounts:
        - name: files
          mountPath: /root/files
        - name: data
          mountPath: /root/.heimdalld
      resources:
        limits:
          cpu: 4000m
          memory: 16Gi
        requests:
          cpu: 4000m
          memory: 16Gi
    ## Rest API Server
    - image:
        repository: maticnetwork/heimdall
        pullPolicy: IfNotPresent
        tag: "v0.2.9"
        command: ["heimdalld", "rest-server"]
      ports:
        - name: rest
          containerPort: 1317
      volumeMounts:
        - name: data
          mountPath: /root/.heimdalld
      resources:
        limits:
          cpu: 2000m
          memory: 8Gi
        requests:
          cpu: 2000m
          memory: 8Gi
  volumes:
    - name: files
      configMap:
        name: '{{ include "base.fullname" . }}-files'
    - name: data
      persistence:
        accessModes:
          - ReadWriteOnce
        size: 1Ti
  configmaps: []
  env:
    fieldRef: []
    configMapKeyRef: []
    secretKeyRef: []
  secrets: []
  services:
    - name: api
      ports:
        - name: rpc
          port: 26657
        - name: rest
          port: 1317
        - name: proxy-app
          port: 26658
    - name: prometheus
      ports:
        - port: 6060
    - name: p2p
      type: NodePort
      ports:
        - name: listener
          port: 30306
  nodeSelector:
    heimdall: node
