apiVersion: v1
kind: Service
metadata:
  name: {{ include "ubuntu.fullname" . }}
  labels:
    {{- include "ubuntu.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.ssh }}
      targetPort: ssh
      protocol: TCP
      name: ssh
    - port: {{ .Values.service.port.netcat }}
      targetPort: netcat
      protocol: TCP
      name: netcat
  selector:
    {{- include "ubuntu.selectorLabels" . | nindent 4 }}
